server:
  port: 8120

spring:
  application:
    name: user-service
  cloud: # 配置注册中心
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8090
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/car_rental?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "021114"
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto  # 主键生成策略，可以是 AUTO（由数据库自动生成，如 IDENTITY、SEQUENCE）、INPUT（手动输入）、ASSIGN_ID（由MyBatisPlus生成）、ASSIGN_UUID（生成UUID）
      logic-delete-value: 1  # 逻辑删除值（未删除时的值）
      logic-not-delete-value: 0  # 逻辑未删除值（已删除时的值）
      column-case: LOWER  # 字段名大小写转换策略，UPPER, LOWER, NONE
      db-column-underline: true  # 是否开启字段名下划线转驼峰命名策略
      date-str-format: yyyy-MM-dd HH:mm:ss  # 日期字符串格式
      logic-delete-field: deleted  # 逻辑删除字段名，如果开启了逻辑删除，需要指定此字段名
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zgf.user.dao.UserDao: debug
